#pragma once

namespace superrogue {
enum class PotionType {
  DAMAGE_POTION,
  DAMAGE_LONG_POTION,
  ARMOR_POTION,
  ARMOR_LONG_POTION,
  HEALTH_POTION,
  HEALTH_BIG_POTION,
  DEXTERITY_POTION,
  DEXTERITY_LONG_POTION
};
};
